# Generated by Django 2.0.4 on 2018-04-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='earthquake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Datetime', models.CharField(max_length=50)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Moment', models.CharField(max_length=50)),
                ('Magnitude', models.CharField(max_length=50)),
                ('Depth', models.FloatField()),
                ('Strike', models.FloatField()),
                ('Dip', models.FloatField()),
                ('Rake', models.FloatField()),
            ],
        ),
    ]
