# Generated by Django 2.0.5 on 2018-07-12 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okada', '0005_earthquake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='earthquake',
        ),
    ]
