# Generated by Django 2.0.7 on 2018-08-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okada', '0006_delete_earthquake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='Etitle',
            field=models.CharField(max_length=100),
        ),
    ]
